version: "3.9"

services:
  backend:
    container_name: kpd-backend
    image: backend:node16-alpine
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - db-network
    ports:
      - "4000:3000" 
    restart: on-failure
  frontend:
    container_name: kpd-frontend
    image: frontend:nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - '8081:80'
    restart: on-failure
  database:
    container_name: kpd-database
    image: postgres:15
    env_file:
      - .env
    networks:
      - db-network
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    restart: on-failure

networks:
  db-network: {}

volumes:
  pg_data: